/* ============================================================================
   Máriás versenykezelő – szótár (magyar / szlovák)

   A program minden felirata innen jön. A nyelv váltható a fejlécben:
     'hu'   – csak magyar
     'sk'   – csak szlovák
     'mind' – magyar / szlovák egyszerre (ez az alapértelmezés, mint a papíron)
   ========================================================================== */
(function (global) {
  'use strict';

  var SZOTAR = {
    hu: {
      /* ---- fejléc, navigáció ---- */
      app_cim: 'Máriás versenykezelő',
      verseny_cim_hely: 'Máriás verseny',
      nav_nevezes: 'Nevezés',
      nav_sorsolas: 'Sorsolás',
      nav_beiras: 'Eredménybeírás',
      nav_rangsor: 'Rangsor',
      nav_vetites: 'Kivetítés',
      nav_nyomtat: 'Nyomtatás',
      nav_beallitas: 'Beállítás',
      nav_sugo: 'Súgó',
      nav_ora: 'Óra',
      ora_cim: 'Visszaszámlálás',
      ora_kor: '{kor}. kör / {osszes} kör',
      ora_vege: 'Vége: {ido}',
      ora_lejart: 'LEJÁRT',
      ora_nincs: 'Az óra nincs elindítva',
      ora_indit: 'Indítás',
      ora_szunet: 'Szünet',
      ora_folytat: 'Folytatás',
      ora_nullaz: 'Nullázás',
      ora_perc: 'Hossz (perc)',
      ora_ablak: 'Külön ablak a kivetítőre',
      ora_ablak_hiba: 'A böngésző nem engedte megnyitni a külön ablakot. Engedélyezd a felugró ablakokat, vagy nyiss egy második lapot ezzel a címmel, és abban válaszd az Óra fület.',
      ora_elindult: 'Az óra elindult: {perc} perc.',
      ora_sugo: 'Az óra a versenyhez tartozik, ezért újratöltés után is ugyanott folytatódik. A „Külön ablak" gombbal egy másik ablakban nyílik meg – azt húzd át a kivetítőre, és közben nyugodtan dolgozhatsz ebben az ablakban.',
      kereso_hely: 'Keresés név szerint…',
      kereso_sugo: 'Ha egy kódot nem találsz, írd be ide a játékos nevének néhány betűjét, és válaszd ki a listából.',
      kereso_mar: 'már nevezve',
      klist_cim: 'Kiemelt játékosok (tartós lista)',
      klist_sugo: 'Ez a lista a versenyektől függetlenül **megmarad**. Aki rajta van, azt a program minden új versenyben automatikusan kiemeltnek jelöli (csillag), és a sorsolásnál külön asztalra kerül. Itt előre összeállíthatod, nyugodtan, a verseny előtt is.',
      klist_ures: 'Még nincs senki a listán. Írd be a nevét vagy a kódját fentebb, és kattints a találatra.',
      klist_mostani: 'A mostani verseny csillagosait hozzáadom',
      klist_mostani_sugo: 'Ha a nevezésnél csillagoztál valakit, azzal egy mozdulattal a tartós listára is felkerül.',
      klist_hozzaadva: '{nev} felkerült a kiemelt-listára.',
      klist_torolve: 'Levettem a kiemelt-listáról.',
      klist_mentve: 'Kész: {n} új játékos a listán, összesen {ossz}.',
      mod_cim: 'Játékmód',
      mod_sugo: 'Kétféleképpen lehet vezetni a versenyt. Az első kör mindkettőnél sorsolás (a kiemelteket a pipával lehet szétszórni vagy véletlenül összeengedni). Utána vagy a svájci rendszer jön (a legjobbak kerülnek egy asztalra), vagy a helycserélő.',
      mod_svajci: 'Svájci (legjobbak egy asztalnál)',
      mod_helycsere: 'Helycserélő (győztes fel, vesztes le)',
      mod_helycsere_sugo: 'A helycserélő rendszer: az asztal első helyezettje EGY asztallal feljebb ül (a 3. helyre), a legrosszabb EGY asztallal lejjebb (az 1. helyre), a második helyezett a helyén marad. Az első asztal győztese és az utolsó asztal legrosszabbja nem mozdul. Ezután a beállított körszám után a program átvált a svájci rendszerre.',
      mod_korok: 'Helycserélő körök száma',
      mod_kesz: 'Játékmód: {mod}.',
      kovetkezo_mod: 'A következő kör a {mod} rendszer szerint készül.',
      uj_kor_kesz_mod: '{kor}. kör kisorsolva ({mod} rendszer szerint).',
      weblap_cim: 'Jelentkezők a weblapról',
      weblap_db: 'A weblapon {n} jelentkező volt ehhez a versenyhez · {k} már regisztrált a helyszínen · {h} még hiányzik.',
      weblap_hianyzo_cim: 'Még nem regisztrált a helyszínen:',
      weblap_mindenki: 'A weblapi jelentkezők mind megérkeztek és regisztráltak. ✓',
      weblap_kattints: 'Kattints a névre, és azzal regisztrálod a versenyre. Aki már megvan, zöld pipát kap.',
      beilleszt_gomb: 'Névsor beillesztése',
      beilleszt_bezar: 'Beillesztő bezárása',
      beilleszt_sugo: 'Másold ide a neveket – soronként egyet, vagy ahogy az Excelből jön (kód + név). A program a törzslista szerint párosítja őket; akit nem talál, azt a megadott névvel veszi fel.',
      beilleszt_hely: 'pl.\n4 Tóth Rudolf\n27 Timko František\nKovács Béla',
      beilleszt_felvesz: 'Felveszem mindet',
      beilleszt_sugo2: 'Aki már nevezve van, azt kihagyja.',
      beilleszt_ures: 'Nem találtam nevet a beillesztett szövegben.',
      beilleszt_kesz: 'Kész: {uj} játékos felvéve ({vendeg} vendégként), {mar} már benevezve volt.',
      weblap_volt: '✓ A weblapon is jelentkezett erre a versenyre.',
      import_cim: 'Verseny átvétele a weblapról',
      import_sugo: 'A weblapon ezt a versenyt indítottad el: {nev} ({datum}), {n} jelentkezővel. Betöltöm az adatait és a jelentkezők listáját?',
      import_gomb: 'Átvétel új versenyként',
      import_elvet: 'Elvetés',
      import_kesz: 'Átvéve a weblapról: {nev} ({n} jelentkező). A jelentkezőket nem vettem fel – ők a Nevezés lapon látszanak, és a helyszínen regisztrálni kell őket.',
      kezdes_cim: 'Először a verseny adatai',
      kezdes_sugo: 'Ez az ajánlott sorrend: add meg, hol és mikor lesz a verseny, hány kör – aztán jöhet a nevezés, végül a sorsolás. (Nem kötelező ebben a sorrendben, bármikor módosítható a Beállítás lapon.) A helyszín írása közben felkínálja a szokásos neveket, és a szlovákot is beírja.',
      kezdes_sugo2: 'Utána írd be a kódokat – a játékosokat bármikor felveheted.',
      kezdes_gomb: 'Rendben, jöhet a nevezés',
      kezdes_kesz: 'Kezdhetjük a nevezést. Sok sikert!',
      kezdes_vissza_sugo: 'A verseny adatai bármikor módosíthatók itt, a Beállítás lapon – az indító adatlap csak az ajánlott sorrend miatt van.',
      kezdes_vissza: 'Indító adatlap újra',
      kezdes_ujra: 'Az indító adatlap újra előjön a Nevezés lapon.',
      folytatva: 'A félbehagyott versenyt betöltöttem: {nev} ({kor}. kör). Folytathatod, ahol abbahagytad.',
      lezar_gomb: 'Verseny lezárása',
      lezar_sugo: 'A lezárás után az eredmény már nem változik, és előjönnek az átadáshoz szükséges gombok.',
      lezar_biztos: 'Lezárjuk a versenyt? Utána már nem írhatók be eredmények.',
      lezar_kesz: 'A verseny lezárva ({kor} kör). Most exportáld és add át a weblapnak.',
      lezarva_jel: 'A verseny le van zárva. Az eredmény végleges.',
      lezarva_feltoltes: 'Átadás a weblapnak',
      kod_vissz_jo: '',
      kod_vissz_mar: '{nev} ({kod}) már nevezve van.',
      kod_vissz_nincs: 'Ez a kód ({kod}) nincs a törzslistán – írd be a nevét a második mezőbe.',
      torzs_cim: 'Játékosok listája (törzslista)',
      torzs_sugo: 'A programban a weblap névsora van beépítve (100 játékos). Ha azóta új játékosokat vettél fel – például 100 fölötti kártyaszámokat –, töltsd be ide a saját listádat. Soronként: kód, kártyaszám, név (az Excelből egyszerűen kimásolva is jó).',
      torzs_gomb: 'Törzslista betöltése fájlból',
      torzs_alap: 'Vissza az alap listára',
      torzs_kesz: 'Betöltve: {n} játékos.',
      torzs_alap_kesz: 'Visszaállt az alap lista ({n} játékos).',
      torzs_hiba: 'Nem sikerült: legalább 10 sort várok, soronként kód, kártyaszám és név.',
      torzs_most: 'Most {n} játékos van a listában.',
      nyelv: 'Nyelv',
      nyelv_kezelo: 'Kezelő',
      nyelv_kivetites: 'Kivetítés',
      vet_nevlista: 'Regisztráltak',
      vet_ablak: 'Külön ablak',
      nevlista_cim: 'Beregsztrált játékosok',
      nevlista_db: '{n} játékos · {t} asztal',
      kor_jelzo: '{kor}. kör / {osszes}',
      kesz_asztal: 'kész {kesz}/{ossz} asztal',
      nincs_sorsolas: 'még nincs sorsolás',
      jatekos_db: '{n} játékos',
      asztal_db: '{n} asztal',
      kiemelt_db: '{n} kiemelt',
      asztal_elosztas: '{t} asztal: {a}×{alap} + {b}×{nagy}',
      minden_asztal_alap: '{t} asztal: mind {alap} fős',
      asztal_elosztas_nagy: '{t} asztal: mind {nagy} fős',
      offline: 'internet nélkül is működik',

      /* ---- következő lépés sáv ---- */
      lepes_felirat: 'Most ez a teendő:',
      lepes_nevezes: 'Nevezd be a játékosokat',
      lepes_nevezes_sugo: 'Írd be a kódot, vagy olvasd be a kártyát, majd Enter.',
      lepes_sorsolas: 'Sorsold ki az 1. kört',
      lepes_sorsolas_sugo: 'Ellenőrizd a kiemelteket, majd nyomd meg a Sorsolás gombot.',
      lepes_beiras: 'Írd be a(z) {asztal}. asztal eredményét',
      lepes_beiras_sugo: 'Még {n} asztal hiányzik ebben a körben.',
      lepes_uj_kor: 'Minden asztal kész – sorsolhatod a(z) {kor}. kört',
      lepes_uj_kor_sugo: 'A rangsor szerint osztja ki a játékosokat.',
      lepes_vege: 'Minden kör kész – nézd meg a rangsort',
      lepes_vege_sugo: 'És mentsd el a versenyt fájlba a Beállítás lapon.',
      lepes_ugras: 'Ugorj oda',

      /* ---- nevezés ---- */
      nevezes_cim: 'Nevezés',
      nevezes_sugo: 'Írd be a rövid kódot, vagy olvasd be a kártyát (a kártyaolvasó úgy viselkedik, mint a billentyűzet), majd Enter. Ha a kód ismeretlen, írd be a nevét is a második mezőbe – a program ad neki kódot.',
      kod_hely: 'kód vagy kártyaszám',
      nev_hely: 'név (csak új játékosnál)',
      hozzaad: 'Hozzáad',
      nevezettek: 'Nevezettek',
      szamlalo_jatekos: 'benevezve',
      szamlalo_asztal: 'asztal',
      szamlalo_kilepett: '({n} kilépett)',
      th_kod: 'Kód',
      th_nev: 'Név',
      th_kartya: 'Kártyakód',
      th_kiemelt: 'Kiemelt',
      uj_verseny: 'Új verseny',
      uj_verseny_kerdes: 'Új verseny indítása? A mostani eredmények törlődnek, a játékoslista megmarad.',
      uj_verseny_kesz: 'Új verseny indítva. Kezdheted a nevezést.',
      torles_kerdes: '{nev} törlése a versenyről?',
      uzen_mar_nevezve: '{nev} már nevezve van ({kod}).',
      uzen_nincs_torzs: 'Ez a kód ({kod}) nincs a törzslistán. Írd be a nevét a második mezőbe, és Enter – ha a neve benne van a listában, azt a játékost veszem fel; ha nem, kódot adok neki. Kereshetsz név szerint is a lenti keresővel.',
      uzen_nevbol_talalva: '{beirt} a listában van: {nev} ({kod}) – így vettem fel, nem vendégként.',
      uzen_nevbol_kozel: 'A beírt névből erre találtam a listában: {nev} ({kod}) – így vettem fel. Ha nem ő az, töröljük és keresd ki a keresőből.',
      uzen_tobb_ilyen_nev: 'Több hasonló nevű játékos van a listában ({n}). Válaszd ki lent a keresőből, melyikre gondoltál – vendégként nem vettem fel.',
      uzen_hozzaadva: '{nev} hozzáadva ({kod}).',
      uzen_vendeg: '{nev} felvéve ({kod}). Ha később kártyát kap, írd be a kártyakódot a listában.',
      uzen_vendeg_kartya: '{nev} felvéve ({kod}), a kártya hozzárendelve.',
      uzen_kod_modositva: 'Kód módosítva: {regi} → {uj}',
      uzen_kod_hasznalt: 'Ez a kód ({kod}) már használatban van.',
      uzen_kod_pozitiv: 'A kód pozitív szám legyen.',
      cimke_vendeg: 'vendég',
      nev_tipp: 'A név átírható',
      megse: 'Mégsem',
      torles_biztos: 'Törlöd: {nev}?',
      torles_kesz: '{nev} törölve a versenyről.',
      kilepes_biztos_most: 'Kilép ebből a körből?',
      kilepes_biztos_kovetkezo: 'Csak a következő körtől lép ki?',
      uj_verseny_biztos: 'Új verseny? Az eredmények törlődnek.',
      nev_tipp: 'A név átírható',
      megse: 'Mégsem',
      torles_biztos: 'Törlöd: {nev}?',
      torles_kesz: '{nev} törölve a versenyről.',
      kilepes_biztos_most: 'Kilép ebből a körből?',
      kilepes_biztos_kovetkezo: 'Csak a következő körtől lép ki?',
      uj_verseny_biztos: 'Új verseny? Az eredmények törlődnek.',
      cimke_kilepett: 'kilépett a {kor}. körtől',
      gomb_kilepes: 'Hazament',
      gomb_torles: 'Törlés',
      gorget_be: 'Automatikus görgetés be',
      gorget_ki: 'Automatikus görgetés ki',
      gorget_sugo: 'Ha nem fér ki mindenki egy képernyőre, ezzel lassan le- és felgördül a lista, hogy mindenki megnézhesse.',
      kor_javitas_figyelem: 'Ez a(z) {kor}. kör javítása. A későbbi körök beosztása nem változik (az már kisorsolódott), de a rangsor és a következő sorsolás már a javított értékkel számol.',
      gomb_visszater: 'Visszalép',
      kilepes_tipp: 'Hazament – a következő körtől nem játszik',
      visszater_tipp: 'Visszatér a versenybe',
      kilepes_kerdes_most: '{nev} nem játszik tovább.\n\nEbben a körben még nincs eredménye, ezért ebből a körből kikerül, és a további körökben sem ül asztalhoz. A megmaradó játékosoknál a várt összeg ehhez igazodik.\n\nRendben?',
      kilepes_kerdes_kovetkezo: '{nev} ebben a körben már játszott, ezért ez a kör még számít.\n\nA következő körtől nem ül asztalhoz.\n\nRendben?',
      kilepes_kesz: '{nev} kilépett a {kor}. körtől ({db} asztalnál vettük ki a helyét). Az addigi eredménye megmarad.',
      visszater_kerdes: '{nev} visszatér a versenybe? A következő sorsolásnál már asztalhoz kerül.',
      visszater_kesz: '{nev} visszatért – a következő sorsolásnál már asztalhoz kerül.',
      keves_aktiv: 'Túl kevés az aktív játékos a sorsoláshoz (legalább 3 kell).',
      fo: 'fő',
      keso_cim: 'Későn érkezett: {nev}',
      keso_sugo_van: 'A(z) {kor}. kör már folyik, eredmény is van benne. Beültetheted az egyik asztalhoz negyedikként, vagy csak a következő körtől játszik.',
      keso_sugo_nincs: 'A(z) {kor}. kör ki van sorsolva, de még nincs benne eredmény. Beültetheted egy asztalhoz, vagy az egész kört újrasorsolhatod vele.',
      keso_asztal: 'Asztal',
      keso_be: 'Beültetés erre az asztalra',
      keso_var: 'Csak a következő körtől',
      keso_ujrasorsol: 'A kör újrasorsolása',
      keso_magyarazat: 'Beültetésnél az asztal négyfős lesz (a pontozás 5 / 3 / 3 / 1, a várt pénzösszeg 20 €). Újrasorsolásnál mindenki új helyet kap – csak akkor, ha még nincs eredmény.',
      keso_be_kesz: '{nev} beült a(z) {asztal}. asztalhoz (most {letszam} fő). Ne felejtsd el beírni a pénzét a(z) {kor}. körben!',
      keso_var_kesz: '{nev} a következő sorsolásnál kap asztalt – addig nem játszik.',
      keso_ujrasorsol_kerdes: 'Újrasorsoljuk a(z) {kor}. kört? A mostani beosztás elvész (eredmény még nincs benne).',
      keso_ujrasorsol_kesz: 'A(z) {kor}. kör újra kiosztva, {asztalok} asztal.',
      keso_van_eredmeny: 'Ebben a körben már van eredmény, ezért nem sorsolom újra. Ültesd be egy asztalhoz, vagy várjon a következő körig.',
      keso_hiba: 'Nem sikerült beültetni. Válassz asztalt!',
      cimke_kiemelt: 'kiemelt',
      kod_tipp: 'A kód módosítható – ha a vendég rendes kártyát kap',
      kiemelt_tipp: 'Kiemelt játékos',
      torles_tipp: 'Törlés a versenyről',
      nincs_nevezve: 'Még nincs senki benevezve. Kezdd a kód beírásával, vagy olvasd be az első kártyát.',
      min_harom: 'A sorsoláshoz legalább 3 játékos kell.',

      /* ---- sorsolás ---- */
      sors_cim: 'Sorsolás',
      sors_elso_cim: '1. kör sorsolása',
      sors_sugo: 'A sorsolás a seed számból számol: ugyanaz a seed mindig ugyanazt a sorsolást adja, tehát bármikor visszaellenőrizhető. Ha nem tetszik, írj be más seedet. A kiemelt játékosok mind külön asztalra kerülnek – ketten soha nem ülnek egy asztalnál.',
      seed_auto: 'Sorsolás azonosítója: {seed}. Minden indításkor és minden sorsolásnál újat kap, nem kell vele foglalkozni.',
      seed_sugo: 'Ezt a számot a program magától állítja: minden indításkor és minden sorsolásnál új véletlen azonosítót ad, tehát nem kell kézzel beírni. Ha meg akarsz ismételni egy korábbi sorsolást, írd be ide a régi azonosítót – ugyanaz a szám ugyanis mindig pontosan ugyanazt a beosztást adja. A 2. körtől már a rangsor dönti el a helyeket, ahhoz nem kell.',
      seed: 'Seed',
      kiemelt_vedelem: 'A kiemeltek nem ülnek egy asztalnál',
      kiemelt_ellenorzes: '✓ A(z) {kiemeltDb} kiemelt játékos {kiemeltDb} különböző asztalnál ül.',
      kiemelt_egyutt_figyelem: '⚠ Figyelem: {egyuttDb} asztalnál ketten is kiemeltek ({hol}).',
      vissza: 'Vissza',
      vet_pont: '{n} pont',
      vet_pont_rovid: 'pont',
      negyfos_hely: '4 fős asztal(ok)',
      negyfos_vegen: 'a végén',
      negyfos_elol: 'az elején',
      negyfos_szetszorva: 'szétszórva',
      sorsol_gomb: 'Sorsolás',
      kiemeltek_felsorolas: 'Kiemeltek ({n}): {nevek}',
      nincs_kiemelt: 'Nincs kiemelt játékos megjelölve – mindenki véletlenszerűen kerül asztalhoz.',
      negyfos_vegen_mindig: 'A négyfős asztalok mindig a sor végére kerülnek (a legutolsó asztalok), hogy az élen mindenhol hárman üljenek.',
      vedelem_ki: 'A kiemelt-védelem ki van kapcsolva: ez pontosan a régi, teljesen véletlen sorsolás.',
      tobb_kiemelt: 'Több kiemelt van ({k}), mint asztal ({t}) – {marad} kiemelt a többiekkel kerül egy asztalra.',
      negyfos_magyarazat: 'A négyfős asztalnál a pontozás 5 / 3 / 3 / 1, és a cédulán is 4 sor lesz.',
      korok_cim: 'Körök',
      korok_sugo: 'Az 1. kör véletlen, de a kiemeltek ilyenkor sem kerülnek egy asztalra. A többi kör a rangsor szerint: a legjobb játékos az 1. asztal első helyére kerül.',
      kor_gomb: '{kor}. kör',
      kovetkezo_kor_gomb: '{kor}. kör sorsolása',
      kor_lezarva_figyelem: 'Előbb minden asztal eredményét írd be.',
      sors_kesz: '1. kör kisorsolva. {figyelem}',
      uj_kor_kesz: '{kor}. kör kisorsolva a rangsor szerint.',
      nincs_jatekos: 'Nincs benevezett játékos.',
      minden_kor_kesz: 'Minden kör lejátszva. A Rangsor lapon látod a végeredményt, a Beállítás lapon adhatod át a weblapnak.',
      beosztas_cim: '{kor}. kör beosztása',
      asztal_szam: '{n}.',
      asztal_cim: '{n}. asztal',

      /* ---- eredménybeírás ---- */
      beir_cim: '{kor}. kör · eredménybeírás',
      beir_sugo: 'Válaszd ki az asztalt (a papíron lévő számot), és írd be a pénzt. A pontot a program számolja a helyezésből (5 / 3 / 1, holtversenynél átlagol) – ha mégis kézzel akarod, kattints a pontra.',
      hianyzo_asztalok: 'Hiányzó asztalok: {lista}',
      kor_minden_kesz: 'Minden asztal kész ebben a körben.',
      th_jatekos: 'Játékos',
      th_penz: '€',
      th_kor_pont: 'Kör pontja',
      eddig: 'eddig {pont} pont · {penz} €',
      mentes_kovetkezo: 'Mentés és következő asztal',
      elozo_asztal: 'Előző asztal',
      kor_lezarasa: 'Kör lezárása és sorsolás',
      penz_rendben: 'a pénz rendben ({penz} €)',
      penz_hiba: 'a pénz összege {ossz} €, a várt {vart} € – nézd át!',
      penz_reszben: '{kesz} / {ossz} kitöltve · várt összeg {vart} €',
      kor_kesz_uzen: 'Minden kör kész.',
      kor_nem_kesz: 'Még nem kész minden asztal ebben a körben.',
      nincs_sorsolas_beir: 'Előbb sorsolni kell (Sorsolás fül).',

      /* ---- rangsor ---- */
      rang_cim: 'Rangsor – {kor} kör után',
      rang_sugo: 'Sorrend: {sorrend}',
      th_hely: '#',
      th_ossz_pont: 'Pont',
      th_ossz_penz: '€',
      th_elso_hely: 'Első hely',
      th_kor: '{kor}. kör',
      th_aszta: 'Asztal',
      dontetlen_ok: '= {szempont}',
      nincs_eredmeny: 'Még nincs eredmény.',
      tb_pont: 'összpont',
      tb_penz: 'összpénz',
      tb_otos: 'kör-első helyezések',
      tb_kozep: 'középső helyezések',
      tb_utolso: 'utolsó helyezések',
      tb_legjobbKor: 'legjobb egy kör',
      tb_kod: 'kód (elfogulatlan)',

      /* ---- kivetítés ---- */
      vet_asztalok: 'Asztalok',
      vet_rangsor: 'Rangsor',
      vet_ki_hol_ul: '{kor}. kör – ki hol ül',
      vet_allas: '{kor}. kör utáni állás',
      vet_nincs_sorsolas: 'Még nincs sorsolás',

      /* ---- nyomtatás ---- */
      nyom_cim: 'Nyomtatás',
      nyom_sugo: 'Asztalonként egy cédula, amire a helyszínen írják rá az eredményt. Fekvő A4-es lap, a cédulák száma laponként állítható – 8 cédula esetén 2 oszlopban, 4 sorban. A négyzetekbe írják az összeget és a pontot.',
      nyom_kor: 'Kör',
      nyom_gomb: 'Nyomtatás',
      nyom_db: 'Papír egy lapon',
      ora_vilagos: 'Világos szín',
      ora_sotet: 'Sötét szín',
      cedula_nev: 'Név',
      cedula_penz: '€',
      cedula_pont: 'Pont',
      cedula_alairas: 'Aláírás',
      cedula_aszta: '{n}. asztal · {kor}. kör',
      cedula_id: 'ID',

      /* ---- beállítás ---- */
      beall_cim: 'Verseny adatai',
      mezo_nev: 'Verseny neve',
      mezo_hely_hu: 'Helyszín (magyarul)',
      mezo_jatekok_tipp: 'Egy körben hány játékot játszanak – csak az ellenőrzéshez.',
      mezo_befizetes_tipp: 'Egy játék befizetése euróban – csak az ellenőrzéshez.',
      penz_mezo_sugo: 'A Játék / kör és a Befizetés / játék csak az ellenőrzéshez kell: ebből számolja a program, mennyi pénznek kell lennie egy asztalon (játékok × befizetés × játékosok). Ha nem használod, hagyd üresen – a program akkor is mindent számol. Az asztal létszáma általában 3; ha mégis négyes asztal lesz, itt állítható.',
      mezo_hely_sk: 'Helyszín (szlovákul)',
      kezdo_szabaly: 'Milyen szabály szerint játsszatok?',
      kezdo_kiemelt: 'A kiemelt játékosok…',
      kezdo_kiemelt_kulon: 'külön asztalra kerüljenek',
      kezdo_kiemelt_egyutt: 'véletlenül ülhessenek együtt',
      hely_tippek: 'Szokásos helyszínek (kattints rá):',
      mezo_hely: 'Helyszín',
      mezo_datum: 'Dátum',
      mezo_korok: 'Körök száma',
      mezo_asztal: 'Asztal létszáma',
      mezo_jatekok: 'Játék / kör',
      mezo_befizetes: 'Befizetés / játék',
      mezo_seed: 'Sorsolási seed',
      beall_sugo: 'A kiemelt-védelem kikapcsolásával a program a régi, teljesen véletlen sorsolást adja. A kiemelteket a Nevezés lapon a csillaggal jelölöd.',
      tiebreak_cim: 'Döntetlen sorrendje',
      tiebreak_sugo: 'Ha két játékosnak ugyanannyi pontja van, ezek a szempontok döntenek, ebben a sorrendben.',
      tiebreak_nincs: 'nincs beállítva – csak a pont és a pénz számít',
      tiebreak_fel: 'Feljebb',
      tiebreak_le: 'Lejjebb',
      mentes_cim: 'Mentés és átadás',
      mentes_sugo: 'Minden változás azonnal mentődik a böngészőbe. A verseny végén készíts fájlt is – ebből kerül fel az eredmény a weblapra, és ebből lehet visszaállítani.',
      export_gomb: 'Mentés fájlba (.json)',
      import_gomb: 'Betöltés fájlból',
      csv_gomb: 'Eredmény CSV-ben',
      visszaallitas_cim: 'Korábbi állapotok',
      export_kesz: 'Elmentve: {fajl}',
      weblap_cim: 'Átadás a weblapnak',
      weblap_sugo: 'A verseny végén innen kerül fel az eredmény a weblap ranglistájára. A weblapon a többi versennyel együtt számolódik a szezon összesítője.',
      weblap_lepesek: '1. itt másold ki a szöveget · 2. a weblapon: Admin → Kézi eredményfelvétel · 3. illeszd be, add meg a helyszínt, a dátumot és a szezont, majd Mentsd',
      weblap_masolas: 'Vágólapra másolása',
      weblap_txt: 'Mentés .txt fájlba',
      weblap_masolva: 'A szöveg a vágólapon van – a weblap Admin oldalán illeszd be.',
      weblap_figyelem: 'A weblap öt körrel számol. Ha kevesebb kört játszottatok, a hiányzó körök 0-val szerepelnek.',
      weblap_sorok: '{n} játékos · {kor} kör',
      bekuld_cim: 'Eredmény beküldése',
      bekuld_cim_szervezo: 'Beérkezett beküldések',
      bekuld_szervezo_sugo: 'A játékosok a cédulán lévő QR-kóddal küldhetik be az eredményt. Itt látod, mi érkezett, és egy kattintással átveheted.',
      bekuld_frissit: 'Beküldések frissítése',
      bekuld_toltes: 'Beküldések betöltése…',
      bekuld_nincs: 'Még nem érkezett beküldés ehhez a versenyhez.',
      bekuld_elfogad: 'Átvétel',
      bekuld_elvet: 'Elvet',
      bekuld_atveve: 'Átvettem: {kor}. kör, {asztal}. asztal.',
      bekuld_nem_egyezik: 'Ez a beküldés nem ehhez az asztalhoz tartozik (időközben változott a beosztás).',
      bekuld_aszta: '{asztal}. asztal · {kor}. kör',
      bekuld_sugo: 'Írd be, mennyi pénzt nyertetek ebben a körben. A pontot a program számolja.',
      bekuld_vart: 'A pénz összege {vart} € kell legyen.',
      bekuld_kuld: 'Küldés',
      bekuld_kuldes: 'Küldés…',
      bekuld_hianyos: 'Minden játékos pénzét írd be!',
      bekuld_elkuldve: 'Elküldve!',
      bekuld_elkuldve_sugo: 'A szervező átveszi, és bekerül a hivatalos eredménybe.',
      bekuld_ujra: 'Új beküldés',
      bekuld_hiba: 'Nem sikerült elküldeni. Írd le a számokat, és add oda a szervezőnek – a papír mindig működik!',
      bekuld_nincs_net: 'Ha nincs internet, nem tud küldeni – ilyenkor a cédulát add oda a szervezőnek.',
      bekuld_hibas_link: 'Ez a beküldő link hiányos. Olvasd be újra a cédulán lévő QR-kódot.',
      bekuld_qr_cim: 'A játékosok beküldhetik telefonról',
      bekuld_qr_sugo: 'Ez a QR-kód a cédulán is rajta van.',
      mezo_webcim: 'A program webcíme (a beküldéshez)',
      beall_webcim_sugo: 'Ha megadod a weblapon futó program címét (pl. https://mub.sk/verseny/verseny.html), a cédulákra QR-kód kerül, és a játékosok telefonról küldhetik be az eredményt. Internet nélkül ez nem működik – a papír út mindig megmarad.',
      beall_esemeny: 'A verseny azonosítója: {id}',
      import_kesz: 'Betöltve: {nev} · {n} játékos',
      import_hiba: 'Nem sikerült betölteni: {uzenet}',
      visszaallit_kerdes: 'Visszaállítod ezt az állapotot? A mostani felülíródik.',
      visszaallitva: 'Visszaállítva.',
      mentes_hiba: 'Nem sikerült elmenteni a böngésző tárolójába. Készíts biztonsági mentést fájlba!',
      nyelv_cim: 'Nyelv',

      /* ---- súgó ---- */
      sugo_cim: 'Így vezesd le a versenyt',
      sugo_1_cim: '1. Nevezés',
      sugo_1: 'Írd be a játékos rövid kódját, vagy olvasd be a kártyáját, majd Enter. Ha nem szerepel a listán, írd be a nevét – kódot a program ad neki. A csillaggal jelölöd, ki számít kiemeltnek.',
      sugo_2_cim: '2. Sorsolás',
      sugo_2: 'Írj be egy seed számot (bármi lehet, akár a mai dátum), és nyomd meg a Sorsolás gombot. Ugyanaz a seed mindig ugyanazt a beosztást adja, ezért bármikor ellenőrizhető; ha nem tetszik, másik számmal újrasorsolhatsz. Ha a kiemelteket nem akarod külön asztalra tenni, vedd ki a pipát – úgy a régi, teljesen véletlen sorsolást kapod.',
      sugo_3_cim: '3. Nyomtatás',
      sugo_3: 'Nyomtasd ki a cédulákat (fekvő A4), és oszd ki az asztalokra. A játékosok a cédulára írják az eredményt.',
      sugo_4_cim: '4. Kivetítés',
      sugo_4: 'A Kivetítés lapon megnézhetik, ki hol ül. Nyiss egy második ablakot ugyanezzel a lappal, és húzd át a kivetítőre.',
      sugo_5_cim: '5. Eredménybeírás',
      sugo_5: 'Amikor behozzák a cédulákat, az Eredménybeírás lapon kiválasztod az asztal számát, és beírod a pénzt. A pontot a program számolja. Ha a pénz összege nem annyi, amennyinek lennie kell, figyelmeztet.',
      sugo_6_cim: '6. Következő kör',
      sugo_6: 'Ha minden asztal kész, a gomb kisorsolja a következő kört a rangsor szerint: a legjobb játékos az 1. asztalra kerül.',
      sugo_7_cim: '7. A végén',
      sugo_7: 'A Beállítás lapon mentsd el a versenyt fájlba, és onnan másold ki az eredményt a weblapra („Átadás a weblapnak"). Ebből lesz a ranglista, és ebből lehet bármikor visszaállítani.',
      sugo_offline_cim: 'Internet nélkül',
      sugo_offline: 'A program minden adatot a saját gépén tárol, internet egyáltalán nem kell hozzá. Ha a böngészőt bezárod, az adatok megmaradnak. A verseny végén azért mentsd fájlba is.',
      sugo_mentes_cim: 'Ha valami elromlana',
      sugo_mentes: 'A Beállítás lapon az utolsó 8 állapot visszaállítható. Ha valamit elrontottál, ott keresd.',
      sugo_megjegyzes: 'A program az Excel táblázat helyett készült: ugyanazt a pontozást használja (a helyezés 5 / 3 / 1, holtversenynél átlagolva), de nem kell benne keresgélni.',

      /* ---- egyéb ---- */
      igen: 'Igen',
      nem: 'Nem',
      bezar: 'Bezár'
    },

    sk: {
      /* ---- hlavička, navigácia ---- */
      app_cim: 'Správa mariášovej súťaže',
      verseny_cim_hely: 'Mariášová súťaž',
      nav_nevezes: 'Prihláška',
      nav_sorsolas: 'Žrebovanie',
      nav_beiras: 'Zápis výsledkov',
      nav_rangsor: 'Poradie',
      nav_vetites: 'Premietanie',
      nav_nyomtat: 'Tlač',
      nav_beallitas: 'Nastavenie',
      nav_sugo: 'Pomoc',
      nav_ora: 'Hodiny',
      ora_cim: 'Odpočítavanie',
      ora_kor: '{kor}. kolo / {osszes} kôl',
      ora_vege: 'Koniec: {ido}',
      ora_lejart: 'ČAS VYPRŠAL',
      ora_nincs: 'Hodiny nie sú spustené',
      ora_indit: 'Štart',
      ora_szunet: 'Pauza',
      ora_folytat: 'Pokračovať',
      ora_nullaz: 'Vynulovať',
      ora_perc: 'Dĺžka (min)',
      ora_ablak: 'Samostatné okno na projektor',
      ora_ablak_hiba: 'Prehliadač nedovolil otvoriť samostatné okno. Povoľ vyskakovacie okná alebo si otvor druhú kartu s touto adresou a vyber v nej kartu Hodiny.',
      ora_elindult: 'Hodiny spustené: {perc} min.',
      ora_sugo: 'Hodiny patria k súťaži, preto po obnovení stránky pokračujú tam, kde boli. Tlačidlom „Samostatné okno" sa otvoria v druhom okne – to presuň na projektor a medzitým môžeš pokojne pracovať v tomto okne.',
      kereso_hely: 'Hľadať podľa mena…',
      kereso_sugo: 'Ak niektorý kód nenájdeš, napíš sem niekoľko písmen mena hráča a vyber ho zo zoznamu.',
      kereso_mar: 'už prihlásený',
      klist_cim: 'Nasadení hráči (trvalý zoznam)',
      klist_sugo: 'Tento zoznam **zostáva** aj medzi súťažami. Kto je na ňom, toho program v každej novej súťaži automaticky označí ako nasadeného (hviezdička) a pri žrebovaní ide k samostatnému stolu. Môžeš si ho pripraviť vopred, ešte pred súťažou.',
      klist_ures: 'V zozname zatiaľ nikto nie je. Napíš hore meno alebo kód a klikni na výsledok.',
      klist_mostani: 'Pridám hviezdičkovaných z tejto súťaže',
      klist_mostani_sugo: 'Ak si pri prihlasovaní niekoho označil hviezdičkou, jedným klikom sa dostane aj do trvalého zoznamu.',
      klist_hozzaadva: '{nev} je v zozname nasadených.',
      klist_torolve: 'Odobral som ho zo zoznamu nasadených.',
      klist_mentve: 'Hotovo: {n} nových v zozname, spolu {ossz}.',
      mod_cim: 'Spôsob hry',
      mod_sugo: 'Súťaž sa dá viesť dvoma spôsobmi. Prvé kolo je v oboch prípadoch žrebovanie (nasadených môžeš fajkou rozhádzať alebo nechať náhodne spolu). Potom nasleduje buď švajčiarsky systém (najlepší k jednému stolu), alebo výmenný.',
      mod_svajci: 'Švajčiarsky (najlepší za jedným stolom)',
      mod_helycsere: 'Výmenný (víťaz hore, porazený dole)',
      mod_helycsere_sugo: 'Výmenný systém: víťaz stola si sadne O JEDEN stôl vyššie (na 3. miesto), najhorší O JEDEN stôl nižšie (na 1. miesto), druhý v poradí zostáva na svojom mieste. Víťaz prvého stola a najhorší z posledného stola sa neposúvajú. Po nastavenom počte kôl program prepne na švajčiarsky systém.',
      mod_korok: 'Počet výmenných kôl',
      mod_kesz: 'Spôsob hry: {mod}.',
      kovetkezo_mod: 'Ďalšie kolo sa vytvorí podľa systému: {mod}.',
      uj_kor_kesz_mod: '{kor}. kolo vyžrebované (systém {mod}).',
      weblap_cim: 'Prihlásení z webu',
      weblap_db: 'Na webe sa prihlásilo {n} hráčov · {k} už zaregistrovaných na mieste · {h} ešte chýba.',
      weblap_hianyzo_cim: 'Ešte nie sú zaregistrovaní na mieste:',
      weblap_mindenki: 'Všetci prihlásení z webu prišli a sú zaregistrovaní. ✓',
      weblap_kattints: 'Klikni na meno a tým ho zaregistruješ do súťaže. Kto už je zaregistrovaný, dostane zelenú fajku.',
      beilleszt_gomb: 'Vložiť zoznam mien',
      beilleszt_bezar: 'Zavrieť vkladanie',
      beilleszt_sugo: 'Skopíruj sem mená – jedno na riadok, alebo tak, ako idú z Excelu (kód + meno). Program ich priradí podľa zoznamu; koho nenájde, toho zapíše s uvedeným menom.',
      beilleszt_hely: 'napr.\n4 Tóth Rudolf\n27 Timko František\nKovács Béla',
      beilleszt_felvesz: 'Zapíšem všetkých',
      beilleszt_sugo2: 'Kto už je prihlásený, toho preskočí.',
      beilleszt_ures: 'V vloženom texte som nenašiel žiadne meno.',
      beilleszt_kesz: 'Hotovo: {uj} hráčov zapísaných ({vendeg} ako hostia), {mar} už bolo prihlásených.',
      weblap_volt: '✓ Na webe sa na tento turnaj tiež prihlásil.',
      import_cim: 'Prevzatie turnaja z webu',
      import_sugo: 'Na webe si spustil tento turnaj: {nev} ({datum}), {n} prihlásených. Načítať jeho údaje a zoznam prihlásených?',
      import_gomb: 'Prevziať ako nový turnaj',
      import_elvet: 'Zahodiť',
      import_kesz: 'Prevzaté z webu: {nev} ({n} prihlásených). Prihlásených som nepridal – vidíš ich na karte Prihlásenie a na mieste ich treba zaregistrovať.',
      kezdes_cim: 'Najprv údaje o súťaži',
      kezdes_sugo: 'Toto je odporúčané poradie: zadaj, kde a kedy bude súťaž, koľko kôl – potom nasleduje prihlasovanie a nakoniec žrebovanie. (Nie je to povinné v tomto poradí, v Nastaveniach sa dá kedykoľvek zmeniť.) Pri písaní miesta sa ponúknu obvyklé názvy a doplní sa aj slovenský.',
      kezdes_sugo2: 'Potom zadávaj kódy – hráčov môžeš prihlásiť kedykoľvek.',
      kezdes_gomb: 'Dobre, môžeme prihlasovať',
      kezdes_kesz: 'Môžeme prihlasovať. Veľa šťastia!',
      kezdes_vissza_sugo: 'Údaje súťaže sa dajú kedykoľvek zmeniť tu, v Nastaveniach – úvodný formulár je len odporúčané poradie.',
      kezdes_vissza: 'Znova úvodný formulár',
      kezdes_ujra: 'Úvodný formulár sa znova zobrazí na karte Prihlásenie.',
      folytatva: 'Nedokončenú súťaž som načítal: {nev} ({kor}. kolo). Môžeš pokračovať tam, kde si skončil.',
      lezar_gomb: 'Uzavrieť súťaž',
      lezar_sugo: 'Po uzavretí sa výsledok už nemení a zobrazia sa tlačidlá na odovzdanie.',
      lezar_biztos: 'Uzavrieť súťaž? Potom sa už nedajú zapisovať výsledky.',
      lezar_kesz: 'Súťaž uzavretá ({kor} kôl). Teraz exportuj a odovzdaj na web.',
      lezarva_jel: 'Súťaž je uzavretá. Výsledok je konečný.',
      lezarva_feltoltes: 'Odovzdanie na web',
      kod_vissz_jo: '',
      kod_vissz_mar: '{nev} ({kod}) je už prihlásený.',
      kod_vissz_nincs: 'Tento kód ({kod}) nie je v zozname – napíš jeho meno do druhého poľa.',
      torzs_cim: 'Zoznam hráčov',
      torzs_sugo: 'V programe je zabudovaný zoznam z webu (100 hráčov). Ak si odvtedy pridal nových hráčov – napríklad karty s číslom nad 100 –, načítaj sem svoj zoznam. Riadok: kód, číslo karty, meno (dá sa skopírovať aj z Excelu).',
      torzs_gomb: 'Načítať zoznam zo súboru',
      torzs_alap: 'Späť na základný zoznam',
      torzs_kesz: 'Načítané: {n} hráčov.',
      torzs_alap_kesz: 'Obnovený základný zoznam ({n} hráčov).',
      torzs_hiba: 'Nepodarilo sa: očakávam aspoň 10 riadkov (kód, číslo karty, meno).',
      torzs_most: 'V zozname je teraz {n} hráčov.',
      nyelv: 'Jazyk',
      nyelv_kezelo: 'Obsluha',
      nyelv_kivetites: 'Projekcia',
      vet_nevlista: 'Prihlásení',
      vet_ablak: 'Samostatné okno',
      nevlista_cim: 'Prihlásení hráči',
      nevlista_db: '{n} hráčov · {t} stolov',
      kor_jelzo: '{kor}. kolo / {osszes}',
      kesz_asztal: 'hotovo {kesz}/{ossz} stolov',
      nincs_sorsolas: 'ešte nie je žrebované',
      jatekos_db: '{n} hráčov',
      asztal_db: '{n} stolov',
      kiemelt_db: '{n} nasadených',
      asztal_elosztas: '{t} stolov: {a}×{alap} + {b}×{nagy}',
      minden_asztal_alap: '{t} stolov: všetky po {alap} hráčoch',
      asztal_elosztas_nagy: '{t} stolov: všetky po {nagy} hráčoch',
      offline: 'funguje aj bez internetu',

      /* ---- ďalší krok ---- */
      lepes_felirat: 'Teraz urob toto:',
      lepes_nevezes: 'Prihlás hráčov',
      lepes_nevezes_sugo: 'Napíš kód alebo načítaj kartu a stlač Enter.',
      lepes_sorsolas: 'Vyžrebuj 1. kolo',
      lepes_sorsolas_sugo: 'Skontroluj nasadených a stlač tlačidlo Žrebovať.',
      lepes_beiras: 'Zapíš výsledok {asztal}. stola',
      lepes_beiras_sugo: 'V tomto kole ešte chýba {n} stolov.',
      lepes_uj_kor: 'Všetky stoly hotové – môžeš žrebovať {kor}. kolo',
      lepes_uj_kor_sugo: 'Hráčov rozdelí podľa poradia.',
      lepes_vege: 'Všetky kolá hotové – pozri si poradie',
      lepes_vege_sugo: 'A ulož súťaž do súboru na karte Nastavenie.',
      lepes_ugras: 'Choď tam',

      /* ---- prihláška ---- */
      nevezes_cim: 'Prihláška',
      nevezes_sugo: 'Napíš krátky kód alebo načítaj kartu (čítačka sa správa ako klávesnica) a stlač Enter. Ak kód nie je v zozname, napíš aj meno – program mu pridelí kód.',
      kod_hely: 'kód alebo číslo karty',
      nev_hely: 'meno (len pri novom hráčovi)',
      hozzaad: 'Pridať',
      nevezettek: 'Prihlásení',
      szamlalo_jatekos: 'prihlásených',
      szamlalo_asztal: 'stolov',
      szamlalo_kilepett: '({n} odišiel)',
      th_kod: 'Kód',
      th_nev: 'Meno',
      th_kartya: 'Kód karty',
      th_kiemelt: 'Nasadený',
      uj_verseny: 'Nová súťaž',
      uj_verseny_kerdes: 'Začať novú súťaž? Terajšie výsledky sa vymažú, zoznam hráčov zostane.',
      uj_verseny_kesz: 'Nová súťaž spustená. Môžeš prihlasovať.',
      torles_kerdes: 'Vymazať {nev} zo súťaže?',
      uzen_mar_nevezve: '{nev} je už prihlásený ({kod}).',
      uzen_nincs_torzs: 'Tento kód ({kod}) nie je v zozname. Napíš jeho meno do druhého poľa a stlač Enter – ak je jeho meno v zozname, prihlásim toho hráča; ak nie, pridelím mu kód. Môžeš hľadať aj podľa mena v hľadáčiku nižšie.',
      uzen_nevbol_talalva: '{beirt} je v zozname: {nev} ({kod}) – prihlásil som ho, nie ako hosťa.',
      uzen_nevbol_kozel: 'Podľa zadaného mena som v zozname našiel: {nev} ({kod}) – prihlásil som ho. Ak to nie je on, zmaž ho a nájdi ho v hľadáčiku.',
      uzen_tobb_ilyen_nev: 'V zozname je viac podobných mien ({n}). Vyber nižšie v hľadáčiku, koho si myslel – ako hosťa som ho neprihlásil.',
      uzen_hozzaadva: '{nev} pridaný ({kod}).',
      uzen_vendeg: '{nev} pridaný ({kod}). Ak neskôr dostane kartu, napíš kód karty do zoznamu.',
      uzen_vendeg_kartya: '{nev} pridaný ({kod}), karta priradená.',
      uzen_kod_modositva: 'Kód zmenený: {regi} → {uj}',
      uzen_kod_hasznalt: 'Tento kód ({kod}) sa už používa.',
      uzen_kod_pozitiv: 'Kód musí byť kladné číslo.',
      cimke_vendeg: 'hosť',
      nev_tipp: 'Meno sa dá prepísať',
      megse: 'Zrušiť',
      torles_biztos: 'Vymazať: {nev}?',
      torles_kesz: '{nev} bol vymazaný zo súťaže.',
      kilepes_biztos_most: 'Odíde z tohto kola?',
      kilepes_biztos_kovetkezo: 'Odíde až od ďalšieho kola?',
      uj_verseny_biztos: 'Nová súťaž? Výsledky sa vymažú.',
      nev_tipp: 'Meno sa dá prepísať',
      megse: 'Zrušiť',
      torles_biztos: 'Vymazať: {nev}?',
      torles_kesz: '{nev} bol vymazaný zo súťaže.',
      kilepes_biztos_most: 'Odíde z tohto kola?',
      cimke_kilepett: 'odišiel od {kor}. kola',
      gomb_kilepes: 'Odišiel',
      gomb_torles: 'Vymazať',
      gorget_be: 'Automatické posúvanie zap.',
      gorget_ki: 'Automatické posúvanie vyp.',
      gorget_sugo: 'Ak sa všetci nezmestia na jednu obrazovku, zoznam sa pomaly posúva dole a hore, aby si to každý mohol pozrieť.',
      kor_javitas_figyelem: 'Toto je oprava {kor}. kola. Rozdelenie neskorších kôl sa nemení (to už bolo vyžrebované), ale poradie a ďalšie žrebovanie už počítajú s opravenou hodnotou.',
      gomb_visszater: 'Návrat',
      kilepes_tipp: 'Odišiel domov – od ďalšieho kola nehrá',
      visszater_tipp: 'Vráti sa do súťaže',
      kilepes_kerdes_most: '{nev} už nehrá.\n\nV tomto kole ešte nemá výsledok, preto vypadne z tohto kola a nebude sedieť za stolom ani v ďalších kolách. Očakávaná suma u ostatných hráčov sa tomu prispôsobí.\n\nV poriadku?',
      kilepes_kerdes_kovetkezo: '{nev} v tomto kole už hral, preto sa toto kolo ešte počíta.\n\nOd ďalšieho kola nebude sedieť za stolom.\n\nV poriadku?',
      kilepes_kesz: '{nev} odišiel od {kor}. kola (vybrali sme ho pri {db} stoloch). Doterajší výsledok mu zostáva.',
      visszater_kerdes: '{nev} sa vráti do súťaže? Pri ďalšom žrebovaní už dostane stôl.',
      visszater_kesz: '{nev} sa vrátil – pri ďalšom žrebovaní už dostane stôl.',
      keves_aktiv: 'Málo aktívnych hráčov na žrebovanie (treba aspoň 3).',
      fo: 'hráčov',
      keso_cim: 'Prišiel neskoro: {nev}',
      keso_sugo_van: '{kor}. kolo už prebieha a má aj výsledky. Môžeš ho posadiť k niektorému stolu ako štvrtého, alebo bude hrať až od ďalšieho kola.',
      keso_sugo_nincs: '{kor}. kolo je vyžrebované, ale ešte bez výsledkov. Môžeš ho posadiť k stolu alebo vyžrebovať celé kolo znova s ním.',
      keso_asztal: 'Stôl',
      keso_be: 'Posadiť k tomuto stolu',
      keso_var: 'Až od ďalšieho kola',
      keso_ujrasorsol: 'Vyžrebovať kolo znova',
      keso_magyarazat: 'Pri posadení bude stôl štvormiestny (bodovanie 5 / 3 / 3 / 1, očakávaný súčet 20 €). Pri novom žrebovaní dostane nové miesto každý – len ak ešte nie sú výsledky.',
      keso_be_kesz: '{nev} si sadol k {asztal}. stolu (teraz {letszam} hráčov). Nezabudni mu zapísať peniaze v {kor}. kole!',
      keso_var_kesz: '{nev} dostane stôl pri ďalšom žrebovaní – dovtedy nehrá.',
      keso_ujrasorsol_kerdes: 'Vyžrebovať {kor}. kolo znova? Terajšie rozdelenie sa stratí (výsledky v ňom ešte nie sú).',
      keso_ujrasorsol_kesz: '{kor}. kolo je znova rozdelené, {asztalok} stolov.',
      keso_van_eredmeny: 'V tomto kole už sú výsledky, preto ho znova nežrebujem. Posaď ho k stolu, alebo počká na ďalšie kolo.',
      keso_hiba: 'Nepodarilo sa posadiť. Vyber stôl!',
      cimke_kiemelt: 'nasadený',
      kod_tipp: 'Kód sa dá zmeniť – keď hosť dostane riadnu kartu',
      kiemelt_tipp: 'Nasadený hráč',
      torles_tipp: 'Vymazať zo súťaže',
      nincs_nevezve: 'Zatiaľ nikto nie je prihlásený. Začni napísaním kódu alebo načítaj prvú kartu.',
      min_harom: 'Na žrebovanie treba aspoň 3 hráčov.',

      /* ---- žrebovanie ---- */
      sors_cim: 'Žrebovanie',
      sors_elso_cim: 'Žrebovanie 1. kola',
      sors_sugo: 'Žrebovanie sa počíta zo seed čísla: rovnaký seed vždy dá rovnaké rozlosovanie, takže sa dá kedykoľvek skontrolovať. Ak sa ti nepáči, napíš iný seed. Nasadení hráči idú vždy k rôznym stolom – dvaja nikdy nesedia za jedným stolom.',
      seed_auto: 'Identifikátor žrebovania: {seed}. Pri každom spustení aj žrebovaní dostane nový, netreba sa ním zaoberať.',
      seed_sugo: 'Toto číslo nastavuje program sám: pri každom spustení a každom žrebovaní dá nový náhodný identifikátor, takže ho netreba zadávať. Ak chceš zopakovať staršie žrebovanie, napíš sem starý identifikátor – rovnaké číslo totiž vždy dá presne to isté rozdelenie. Od 2. kola rozhoduje o miestach poradie, tam sa seed nepoužíva.',
      seed: 'Seed',
      kiemelt_vedelem: 'Nasadení nesedia za jedným stolom',
      kiemelt_ellenorzes: '✓ {kiemeltDb} nasadených hráčov sedí za {kiemeltDb} rôznymi stolmi.',
      kiemelt_egyutt_figyelem: '⚠ Pozor: pri {egyuttDb} stoloch sú dvaja nasadení ({hol}).',
      vissza: 'Späť',
      vet_pont: '{n} bodov',
      vet_pont_rovid: 'body',
      negyfos_hely: '4-miestne stoly',
      negyfos_vegen: 'na konci',
      negyfos_elol: 'na začiatku',
      negyfos_szetszorva: 'roztrúsené',
      sorsol_gomb: 'Žrebovať',
      kiemeltek_felsorolas: 'Nasadení ({n}): {nevek}',
      nincs_kiemelt: 'Nie je označený žiadny nasadený hráč – všetci sa rozdelia náhodne.',
      negyfos_vegen_mindig: 'Štvormiestne stoly idú vždy na koniec (posledné stoly), aby vpredu sedeli všade traja.',
      vedelem_ki: 'Ochrana nasadených je vypnutá: toto je presne staré, úplne náhodné žrebovanie.',
      tobb_kiemelt: 'Nasadených je viac ({k}) ako stolov ({t}) – {marad} nasadený pôjde k ostatným.',
      negyfos_magyarazat: 'Pri 4-miestnom stole je bodovanie 5 / 3 / 3 / 1 a na lístku budú 4 riadky.',
      korok_cim: 'Kolá',
      korok_sugo: '1. kolo je náhodné, ale nasadení sa ani vtedy nedostanú k jednému stolu. Ďalšie kolá podľa poradia: najlepší hráč ide na 1. stôl na prvé miesto.',
      kor_gomb: '{kor}. kolo',
      kovetkezo_kor_gomb: 'Žrebovať {kor}. kolo',
      kor_lezarva_figyelem: 'Najprv zapíš výsledky všetkých stolov.',
      sors_kesz: '1. kolo vyžrebované. {figyelem}',
      uj_kor_kesz: '{kor}. kolo vyžrebované podľa poradia.',
      nincs_jatekos: 'Nie sú prihlásení žiadni hráči.',
      minden_kor_kesz: 'Všetky kolá odohraté. Konečný výsledok vidíš na karte Poradie, na karte Nastavenie ho odovzdáš webu.',
      beosztas_cim: 'Rozdelenie {kor}. kola',
      asztal_szam: '{n}.',
      asztal_cim: '{n}. stôl',

      /* ---- zápis výsledkov ---- */
      beir_cim: '{kor}. kolo · zápis výsledkov',
      beir_sugo: 'Vyber stôl (číslo z papiera) a zapíš peniaze. Body spočíta program z umiestnenia (5 / 3 / 1, pri remíze priemer) – ak to chceš ručne, klikni na body.',
      hianyzo_asztalok: 'Chýbajúce stoly: {lista}',
      kor_minden_kesz: 'V tomto kole sú všetky stoly hotové.',
      th_jatekos: 'Hráč',
      th_penz: '€',
      th_kor_pont: 'Body v kole',
      eddig: 'doteraz {pont} bodov · {penz} €',
      mentes_kovetkezo: 'Uložiť a ďalší stôl',
      elozo_asztal: 'Predchádzajúci stôl',
      kor_lezarasa: 'Uzavrieť kolo a žrebovať',
      penz_rendben: 'peniaze sú v poriadku ({penz} €)',
      penz_hiba: 'súčet je {ossz} €, očakávaných {vart} € – skontroluj!',
      penz_reszben: '{kesz} / {ossz} vyplnené · očakávaná suma {vart} €',
      kor_kesz_uzen: 'Všetky kolá hotové.',
      kor_nem_kesz: 'V tomto kole ešte nie sú hotové všetky stoly.',
      nincs_sorsolas_beir: 'Najprv treba žrebovať (karta Žrebovanie).',

      /* ---- poradie ---- */
      rang_cim: 'Poradie – po {kor} kolách',
      rang_sugo: 'Poradie: {sorrend}',
      th_hely: '#',
      th_ossz_pont: 'Body',
      th_ossz_penz: '€',
      th_elso_hely: 'Prvé miesta',
      th_kor: '{kor}. kolo',
      th_aszta: 'Stôl',
      dontetlen_ok: '= {szempont}',
      nincs_eredmeny: 'Zatiaľ žiadny výsledok.',
      tb_pont: 'spolu body',
      tb_penz: 'spolu peniaze',
      tb_otos: 'prvé miesta v kolách',
      tb_kozep: 'stredné umiestnenia',
      tb_utolso: 'posledné umiestnenia',
      tb_legjobbKor: 'najlepšie jedno kolo',
      tb_kod: 'kód (nestranné)',

      /* ---- premietanie ---- */
      vet_asztalok: 'Stoly',
      vet_rangsor: 'Poradie',
      vet_ki_hol_ul: '{kor}. kolo – kto kde sedí',
      vet_allas: 'Stav po {kor}. kole',
      vet_nincs_sorsolas: 'Ešte nie je žrebované',

      /* ---- tlač ---- */
      nyom_cim: 'Tlač',
      nyom_sugo: 'Pre každý stôl jeden lístok, na ktorý na mieste zapíšu výsledok. A4 na šírku, počet lístkov na stránku sa dá nastaviť – pri 8 lístkoch 2 stĺpce, 4 riadky. Do štvorčekov zapíšu sumu a body.',
      nyom_kor: 'Kolo',
      nyom_gomb: 'Tlačiť',
      nyom_db: 'Lístkov na stránku',
      ora_vilagos: 'Svetlé farby',
      ora_sotet: 'Tmavé farby',
      cedula_nev: 'Meno',
      cedula_penz: '€',
      cedula_pont: 'Pont',
      cedula_alairas: 'Podpis',
      cedula_aszta: '{n}. stôl · {kor}. kolo',
      cedula_id: 'ID',

      /* ---- nastavenie ---- */
      beall_cim: 'Údaje o súťaži',
      mezo_nev: 'Názov súťaže',
      mezo_hely_hu: 'Miesto (maďarsky)',
      mezo_jatekok_tipp: 'Koľko hier sa hrá v jednom kole – len na kontrolu.',
      mezo_befizetes_tipp: 'Vklad na jednu hru v eurách – len na kontrolu.',
      penz_mezo_sugo: 'Hry / kolo a Vklad / hra slúžia len na kontrolu: program z toho počíta, koľko peňazí má byť na stole (hry × vklad × hráči). Ak ich nepoužívaš, nechaj prázdne – program počíta aj tak. Počet hráčov za stolom je zvyčajne 3; ak predsa len bude štvormiestny stôl, tu sa dá nastaviť.',
      mezo_hely_sk: 'Miesto (slovensky)',
      kezdo_szabaly: 'Podľa akého systému hráte?',
      kezdo_kiemelt: 'Nasadení hráči…',
      kezdo_kiemelt_kulon: 'nech sedia za rôznymi stolmi',
      kezdo_kiemelt_egyutt: 'môžu sedieť aj spolu',
      hely_tippek: 'Obvyklé miesta (klikni):',
      mezo_hely: 'Miesto',
      mezo_datum: 'Dátum',
      mezo_korok: 'Počet kôl',
      mezo_asztal: 'Počet hráčov pri stole',
      mezo_jatekok: 'Hry / kolo',
      mezo_befizetes: 'Vklad / hra',
      mezo_seed: 'Seed žrebovania',
      beall_sugo: 'Vypnutím ochrany nasadených dostaneš staré, úplne náhodné žrebovanie. Nasadených označíš hviezdičkou na karte Prihláška.',
      tiebreak_cim: 'Poradie pri remíze',
      tiebreak_sugo: 'Ak majú dvaja hráči rovnaký počet bodov, rozhodujú tieto kritériá v tomto poradí.',
      tiebreak_nincs: 'nie je nastavené – rozhodujú len body a peniaze',
      tiebreak_fel: 'Vyššie',
      tiebreak_le: 'Nižšie',
      mentes_cim: 'Uloženie a odovzdanie',
      mentes_sugo: 'Každá zmena sa hneď ukladá do prehliadača. Na konci súťaže urob aj súbor – z neho sa dostane výsledok na web a z neho sa dá obnoviť.',
      export_gomb: 'Uložiť do súboru (.json)',
      import_gomb: 'Načítať zo súboru',
      csv_gomb: 'Výsledok do CSV',
      visszaallitas_cim: 'Predchádzajúce stavy',
      export_kesz: 'Uložené: {fajl}',
      weblap_cim: 'Odovzdanie na web',
      weblap_sugo: 'Na konci súťaže sa odtiaľto dostane výsledok do poradia na webe. Na webe sa spočíta spolu s ostatnými turnajmi do súhrnu sezóny.',
      weblap_lepesek: '1. tu skopíruj text · 2. na webe: Admin → Ručný zápis výsledkov · 3. vlož ho, zadaj miesto, dátum a sezónu, potom Ulož',
      weblap_masolas: 'Kopírovať do schránky',
      weblap_txt: 'Uložiť do .txt',
      weblap_masolva: 'Text je v schránke – vlož ho na Admin stránke webu.',
      weblap_figyelem: 'Web počíta s piatimi kolami. Ak ste odohrali menej kôl, chýbajúce kolá budú 0.',
      weblap_sorok: '{n} hráčov · {kor} kôl',
      bekuld_cim: 'Odoslanie výsledku',
      bekuld_cim_szervezo: 'Došlé odoslania',
      bekuld_szervezo_sugo: 'Hráči môžu poslať výsledok cez QR kód na lístku. Tu vidíš, čo prišlo, a jedným kliknutím to prevezmeš.',
      bekuld_frissit: 'Obnoviť odoslania',
      bekuld_toltes: 'Načítavam odoslania…',
      bekuld_nincs: 'K tejto súťaži zatiaľ nič neprišlo.',
      bekuld_elfogad: 'Prevziať',
      bekuld_elvet: 'Zamietnuť',
      bekuld_atveve: 'Prevzaté: {kor}. kolo, {asztal}. stôl.',
      bekuld_nem_egyezik: 'Toto odoslanie nepatrí k tomuto stolu (medzitým sa zmenilo rozdelenie).',
      bekuld_aszta: '{asztal}. stôl · {kor}. kolo',
      bekuld_sugo: 'Napíš, koľko peňazí ste v tomto kole vyhrali. Body spočíta program.',
      bekuld_vart: 'Súčet peňazí má byť {vart} €.',
      bekuld_kuld: 'Odoslať',
      bekuld_kuldes: 'Odosielam…',
      bekuld_hianyos: 'Vyplň peniaze všetkým hráčom!',
      bekuld_elkuldve: 'Odoslané!',
      bekuld_elkuldve_sugo: 'Organizátor to prevezme a dostane sa to do oficiálneho výsledku.',
      bekuld_ujra: 'Nové odoslanie',
      bekuld_hiba: 'Nepodarilo sa odoslať. Zapíš si čísla a odovzdaj ich organizátorovi – papier funguje vždy!',
      bekuld_nincs_net: 'Bez internetu sa odoslať nedá – v takom prípade odovzdaj lístok organizátorovi.',
      bekuld_hibas_link: 'Tento odkaz je neúplný. Naskenuj QR kód z lístka znova.',
      bekuld_qr_cim: 'Hráči môžu poslať výsledok z telefónu',
      bekuld_qr_sugo: 'Tento QR kód je aj na lístku.',
      mezo_webcim: 'Webová adresa programu (na odosielanie)',
      beall_webcim_sugo: 'Ak zadáš adresu programu na webe (napr. https://mub.sk/verseny/verseny.html), na lístky sa dostane QR kód a hráči môžu poslať výsledok z telefónu. Bez internetu to nefunguje – papierová cesta zostáva vždy.',
      beall_esemeny: 'Identifikátor súťaže: {id}',
      import_kesz: 'Načítané: {nev} · {n} hráčov',
      import_hiba: 'Nepodarilo sa načítať: {uzenet}',
      visszaallit_kerdes: 'Obnoviť tento stav? Terajší sa prepíše.',
      visszaallitva: 'Obnovené.',
      mentes_hiba: 'Nepodarilo sa uložiť do prehliadača. Urob si zálohu do súboru!',
      nyelv_cim: 'Jazyk',

      /* ---- pomoc ---- */
      sugo_cim: 'Takto odveď súťaž',
      sugo_1_cim: '1. Prihláška',
      sugo_1: 'Napíš krátky kód hráča alebo načítaj jeho kartu a stlač Enter. Ak nie je v zozname, napíš jeho meno – kód mu pridelí program. Hviezdičkou označíš nasadených.',
      sugo_2_cim: '2. Žrebovanie',
      sugo_2: 'Napíš seed číslo (môže byť hocijaké, napríklad dnešný dátum) a stlač tlačidlo Žrebovať. Rovnaký seed vždy dá rovnaké rozdelenie, preto sa dá kedykoľvek skontrolovať; ak sa ti nepáči, žrebuj znova s iným číslom. Ak nechceš nasadených k samostatným stolom, odober fajku – dostaneš staré, úplne náhodné žrebovanie.',
      sugo_3_cim: '3. Tlač',
      sugo_3: 'Vytlač lístky (A4 na šírku) a rozdaj ich na stoly. Hráči píšu výsledok na lístok.',
      sugo_4_cim: '4. Premietanie',
      sugo_4: 'Na karte Premietanie vidia, kto kde sedí. Otvor druhé okno s tou istou stránkou a presuň ho na projektor.',
      sugo_5_cim: '5. Zápis výsledkov',
      sugo_5: 'Keď prinesú lístky, na karte Zápis výsledkov vyberieš číslo stola a zapíšeš peniaze. Body spočíta program. Ak suma nie je taká, aká má byť, upozorní ťa.',
      sugo_6_cim: '6. Ďalšie kolo',
      sugo_6: 'Keď sú všetky stoly hotové, tlačidlo vyžrebuje ďalšie kolo podľa poradia: najlepší hráč ide na 1. stôl.',
      sugo_7_cim: '7. Na konci',
      sugo_7: 'Na karte Nastavenie ulož súťaž do súboru a odtiaľ skopíruj výsledok na web („Odovzdanie na web"). Z neho bude poradie a dá sa z neho kedykoľvek obnoviť.',
      sugo_offline_cim: 'Bez internetu',
      sugo_offline: 'Program ukladá všetky údaje na tvojom počítači, internet nepotrebuje vôbec. Keď zavrieš prehliadač, údaje zostanú. Na konci súťaže to predsa ulož aj do súboru.',
      sugo_mentes_cim: 'Ak sa niečo pokazí',
      sugo_mentes: 'Na karte Nastavenie sa dá obnoviť posledných 8 stavov. Ak si niečo pokazil, hľadaj tam.',
      sugo_megjegyzes: 'Program vznikol namiesto Excel tabuľky: používa rovnaké bodovanie (umiestnenie 5 / 3 / 1, pri remíze priemer), ale nemusíš v ňom nič hľadať.',

      /* ---- ostatné ---- */
      igen: 'Áno',
      nem: 'Nie',
      bezar: 'Zavrieť'
    }
  };

  /* Ezeknél "magyar / szlovák" módban sortöréssel, kisebb betűvel írjuk a szlovákot. */
  var HOSSZU = {
    nevezes_sugo: 1, sors_sugo: 1, beir_sugo: 1, beall_sugo: 1, tiebreak_sugo: 1,
    mentes_sugo: 1, korok_sugo: 1, sugo_1: 1, sugo_2: 1, sugo_3: 1, sugo_4: 1,
    sugo_5: 1, sugo_6: 1, sugo_7: 1, sugo_offline: 1, sugo_mentes: 1, sugo_megjegyzes: 1,
    vedelem_ki: 1, nincs_kiemelt: 1, min_harom: 1, nincs_nevezve: 1, nincs_sorsolas_beir: 1,
    nincs_eredmeny: 1, minden_kor_kesz: 1, kor_minden_kesz: 1, negyfos_magyarazat: 1
  };

  var Nyelv = {
    mod: 'mind',

    modok: ['mind', 'hu', 'sk'],

    /* {hely} behelyettesítés */
    behelyettesit: function (sablon, ertekek) {
      if (!ertekek) return sablon;
      return String(sablon).replace(/\{(\w+)\}/g, function (teljes, kulcs) {
        return (ertekek[kulcs] === undefined || ertekek[kulcs] === null) ? teljes : String(ertekek[kulcs]);
      });
    },

    /* egy kulcs szövege a beállított nyelven */
    sz: function (kulcs, ertekek) {
      var hu = SZOTAR.hu[kulcs];
      var sk = SZOTAR.sk[kulcs];
      if (hu === undefined) return kulcs;                 // hiányzó kulcs – látszik, hogy pótolni kell
      if (sk === undefined) sk = hu;
      var mod = Nyelv.mod || 'mind';
      var s;
      if (mod === 'sk') s = sk;
      else if (mod === 'hu') s = hu;
      else s = (hu === sk) ? hu : (hu + ' / ' + sk);
      s = Nyelv.behelyettesit(s, ertekek);
      return s;
    },

    /* HTML-be való szöveg: "mind" módban a szlovák külön sorban, halványan */
    szhHtml: function (kulcs, ertekek) {
      var hu = SZOTAR.hu[kulcs];
      var sk = SZOTAR.sk[kulcs];
      if (hu === undefined) return kulcs;
      if (sk === undefined) sk = hu;
      var mod = Nyelv.mod || 'mind';
      if (mod === 'sk') return Nyelv.behelyettesit(sk, ertekek);
      if (mod === 'hu') return Nyelv.behelyettesit(hu, ertekek);
      var h = Nyelv.behelyettesit(hu, ertekek);
      var s2 = Nyelv.behelyettesit(sk, ertekek);
      if (h === s2) return h;
      if (HOSSZU[kulcs]) return h + '<span class="sk-sor">' + s2 + '</span>';
      return h + ' / ' + s2;
    },

    /* megvan-e a kulcs mindkét nyelven (a teszthez) */
    hianyzo: function () {
      var ki = [];
      for (var k in SZOTAR.hu) {
        if (!SZOTAR.hu.hasOwnProperty(k)) continue;
        if (SZOTAR.sk[k] === undefined) ki.push(k);
      }
      for (var k2 in SZOTAR.sk) {
        if (!SZOTAR.sk.hasOwnProperty(k2)) continue;
        if (SZOTAR.hu[k2] === undefined) ki.push('sk:' + k2);
      }
      return ki;
    },

    kulcsok: function () { var ki = []; for (var k in SZOTAR.hu) if (SZOTAR.hu.hasOwnProperty(k)) ki.push(k); return ki; }
  };

  global.NYELV = Nyelv;
  if (typeof module !== 'undefined' && module.exports) module.exports = Nyelv;

})(typeof window !== 'undefined' ? window : globalThis);
